# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 13) do

  create_table "activities", :force => true do |t|
    t.column "name",       :string
    t.column "updated_at", :datetime
    t.column "created_at", :datetime
  end

  create_table "activity_logs", :force => true do |t|
    t.column "activity_id", :integer
    t.column "student_id",  :integer
    t.column "lesson_id",   :integer
    t.column "course_id",   :integer
    t.column "date",        :date
    t.column "updated_at",  :datetime
    t.column "created_at",  :datetime
  end

  add_index "activity_logs", ["student_id", "activity_id"], :name => "index_activity_logs_on_student_id_and_activity_id"
  add_index "activity_logs", ["activity_id"], :name => "index_activity_logs_on_activity_id"

  create_table "assignment_logs", :force => true do |t|
    t.column "assignment_id",  :integer
    t.column "course_id",      :integer
    t.column "student_id",     :integer
    t.column "grade",          :integer,  :limit => 1
    t.column "due_date",       :datetime
    t.column "submitted_date", :datetime
    t.column "updated_at",     :datetime
    t.column "created_at",     :datetime
  end

  add_index "assignment_logs", ["student_id", "assignment_id"], :name => "index_assignment_logs_on_student_id_and_assignment_id"
  add_index "assignment_logs", ["assignment_id"], :name => "index_assignment_logs_on_assignment_id"

  create_table "assignments", :force => true do |t|
    t.column "name",         :string
    t.column "description",  :text
    t.column "grading_type", :integer,  :limit => 1
    t.column "min_grade",    :integer,  :limit => 1
    t.column "max_grade",    :integer,  :limit => 1
    t.column "updated_at",   :datetime
    t.column "created_at",   :datetime
  end

  create_table "attendance_types", :force => true do |t|
    t.column "name", :string
  end

  create_table "attendances", :force => true do |t|
    t.column "attendance_type_id", :integer
    t.column "lesson_id",          :integer
    t.column "course_id",          :integer
    t.column "student_id",         :integer
    t.column "date",               :date
    t.column "updated_at",         :datetime
    t.column "created_at",         :datetime
  end

  create_table "coursenotes", :force => true do |t|
    t.column "lesson_id",  :integer
    t.column "course_id",  :integer
    t.column "text",       :text
    t.column "date",       :date
    t.column "updated_at", :datetime
    t.column "created_at", :datetime
  end

  create_table "courseplans", :force => true do |t|
    t.column "lesson_id",  :integer
    t.column "course_id",  :integer
    t.column "text",       :text
    t.column "date",       :date
    t.column "updated_at", :datetime
    t.column "created_at", :datetime
  end

  create_table "courses", :force => true do |t|
    t.column "name",       :string
    t.column "section",    :string
    t.column "grade",      :integer
    t.column "updated_at", :datetime
    t.column "created_at", :datetime
  end

  create_table "enrollments", :force => true do |t|
    t.column "course_id",  :integer
    t.column "student_id", :integer
    t.column "updated_at", :datetime
    t.column "created_at", :datetime
  end

  add_index "enrollments", ["student_id", "course_id"], :name => "index_enrollments_on_student_id_and_course_id"
  add_index "enrollments", ["course_id"], :name => "index_enrollments_on_course_id"

  create_table "lessons", :force => true do |t|
    t.column "course_id",  :integer,  :null => false
    t.column "date",       :date
    t.column "start_time", :time
    t.column "end_time",   :time
    t.column "room",       :integer
    t.column "updated_at", :datetime
    t.column "created_at", :datetime
  end

  create_table "students", :force => true do |t|
    t.column "first_name",  :string
    t.column "middle_name", :string
    t.column "last_name",   :string
    t.column "nickname",    :string
    t.column "gender",      :string
    t.column "updated_at",  :datetime
    t.column "created_at",  :datetime
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
  end

end
